name: PHP Codesniffer

on: [push]

jobs:
  phpcs:
    name: PHP Codesniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      
      - name: Install dependencies
        run: composer install --dev --prefer-dist --no-progress --no-suggest --no-interaction
        
      - name: PHPCS check
        run: vendor/bin/phpcs