name: PHP Unit

on: [push]

jobs:
  build-test:
    name: PHP Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install --dev --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run PHP Unit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
          
      - name: Upload Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml # optional
          flags: unittests
          fail_ci_if_error: true
          verbose: true