name: PHP Unit

on: [push]

jobs:
  build-test:
    name: PHP Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v2
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v6
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text